const FETCH_TRANSACTION_CATEGORIES     = 'fixdin/categories/FETCH_TRANSACTION_CATEGORIES';
const SAVE_TRANSACTION_CATEGORY        = 'fixdin/categories/SAVE_TRANSACTION_CATEGORY';
const EDIT_TRANSACTION_CATEGORY        = 'fixdin/categories/EDIT_TRANSACTION_CATEGORY';
const FINISH_EDIT_TRANSACTION_CATEGORY = 'fixdin/categories/FINISH_EDIT_TRANSACTION_CATEGORY';
const DELETE_TRANSACTION_CATEGORY      = 'fixdin/categories/DELETE_TRANSACTION_CATEGORY';

export default {
    FETCH_TRANSACTION_CATEGORIES,
    SAVE_TRANSACTION_CATEGORY,
    EDIT_TRANSACTION_CATEGORY,
    FINISH_EDIT_TRANSACTION_CATEGORY,
    DELETE_TRANSACTION_CATEGORY
};