const FETCH_BALANCE                   = "fixdin/balances/FETCH_BALANCE";
const FETCH_PENDING_INCOMES_BALANCES  = "fixdin/balances/FETCH_PENDING_INCOMES_BALANCES";
const FETCH_PENDING_EXPENSES_BALANCES = "fixdin/balances/FETCH_PENDING_EXPENSES_BALANCES";
const FETCH_DETAILED_ACCOUNTS_BALANCE = "fixdin/balances/FETCH_DETAILED_ACCOUNTS_BALANCE"; //API effective-incomes-expenses

export default {
    FETCH_BALANCE,
    FETCH_PENDING_INCOMES_BALANCES,
    FETCH_PENDING_EXPENSES_BALANCES,
    FETCH_DETAILED_ACCOUNTS_BALANCE
};