const FETCH_PLAIN_BALANCE             = "fixdin/balances/FETCH_PLAIN_BALANCE";
const FETCH_DETAILED_BALANCE          = "fixdin/balances/FETCH_DETAILED_BALANCE";
const FETCH_ACCOUNTS_DETAILED_BALANCE = "fixdin/balances/FETCH_ACCOUNTS_DETAILED_BALANCE";
const FETCH_PERIODS_BALANCE           = "fixdin/balances/FETCH_PERIODS_BALANCE";

export default {
    FETCH_PLAIN_BALANCE,
    FETCH_DETAILED_BALANCE,
    FETCH_ACCOUNTS_DETAILED_BALANCE,
    FETCH_PERIODS_BALANCE
};