const FETCH_TRANSACTIONS =                'fixdin/transactions/FETCH_TRANSACTIONS';
const COPY_TRANSACTION =                  'fixdin/transactions/COPY_TRANSACTION';
const EDIT_TRANSACTION =                  'fixdin/transactions/EDIT_TRANSACTION';
const FINISH_EDIT_TRANSACTION =           'fixdin/transactions/FINISH_EDIT_TRANSACTION';
const FILTER_TRANSACTIONS =               'fixdin/transactions/FILTER_TRANSACTIONS';
const CLEAR_FILTERS =                     'fixdin/transactions/CLEAR_FILTERS';

const SAVE_TRANSACTION =                  'fixdin/transactions/SAVE_TRANSACTION';
const SAVE_ALL_PERIODIC_TRANSACTIONS =    'fixdin/transactions/SAVE_ALL_PERIODIC_TRANSACTIONS';
const SAVE_THIS_AND_NEXT_TRANSACTIONS =   'fixdin/transactions/SAVE_THIS_AND_NEXT_TRANSACTIONS';

const DELETE_TRANSACTION =                'fixdin/transactions/DELETE_TRANSACTION';
const DELETE_ALL_PERIODIC_TRANSACTIONS =  'fixdin/transactions/DELETE_ALL_PERIODIC_TRANSACTIONS';
const DELETE_THIS_AND_NEXT_TRANSACTIONS = 'fixdin/transactions/DELETE_THIS_AND_NEXT_TRANSACTIONS';

export default {
    FETCH_TRANSACTIONS,
    FILTER_TRANSACTIONS,
    CLEAR_FILTERS,
    SAVE_TRANSACTION,
    SAVE_ALL_PERIODIC_TRANSACTIONS,
    SAVE_THIS_AND_NEXT_TRANSACTIONS,
    COPY_TRANSACTION,
    EDIT_TRANSACTION,
    FINISH_EDIT_TRANSACTION,
    DELETE_TRANSACTION,
    DELETE_ALL_PERIODIC_TRANSACTIONS,
    DELETE_THIS_AND_NEXT_TRANSACTIONS
};