const FETCH_TRANSACTIONS =                'fixdin/transactions/FETCH_TRANSACTIONS';
const SAVE_TRANSACTION =                  'fixdin/transactions/SAVE_TRANSACTION';
const COPY_TRANSACTION =                  'fixdin/transactions/COPY_TRANSACTION';

const EDIT_TRANSACTION =                  'fixdin/transactions/EDIT_TRANSACTION';
const EDIT_ALL_PERIODIC_TRANSACTIONS =    'fixdin/transactions/EDIT_ALL_PERIODIC_TRANSACTIONS';
const EDIT_THIS_AND_NEXT_TRANSACTIONS =   'fixdin/transactions/EDIT_THIS_AND_NEXT_TRANSACTIONS';

const FINISH_EDIT_TRANSACTION =           'fixdin/transactions/FINISH_EDIT_TRANSACTION';

const DELETE_TRANSACTION =                'fixdin/transactions/DELETE_TRANSACTION';
const DELETE_ALL_PERIODIC_TRANSACTIONS =  'fixdin/transactions/DELETE_ALL_PERIODIC_TRANSACTIONS';
const DELETE_THIS_AND_NEXT_TRANSACTIONS = 'fixdin/transactions/DELETE_THIS_AND_NEXT_TRANSACTIONS';

export default {
    FETCH_TRANSACTIONS,
    SAVE_TRANSACTION,
    COPY_TRANSACTION,
    EDIT_TRANSACTION,
    FINISH_EDIT_TRANSACTION,
    DELETE_TRANSACTION,
    DELETE_ALL_PERIODIC_TRANSACTIONS,
    DELETE_THIS_AND_NEXT_TRANSACTIONS
};