const FETCH_LAST_13_MONTHS = "fixdin/reports/FETCH_LAST_13_MONTHS";
const FETCH_PENDING_EXPENSES = "fixdin/reports/FETCH_PENDING_EXPENSES";

export default {
    FETCH_LAST_13_MONTHS,
    FETCH_PENDING_EXPENSES
};