const FETCH_LAST_13_MONTHS = "fixdin/reports/FETCH_LAST_13_MONTHS";
const FETCH_PENDING_TRANSACTIONS = "fixdin/reports/FETCH_PENDING_TRANSACTIONS";
const FETCH_VALUES_BY_CATEGORY = 'fixdin/reports/FETCH_VALUES_BY_CATEGORY';

export default {
    FETCH_LAST_13_MONTHS,
    FETCH_PENDING_TRANSACTIONS,
    FETCH_VALUES_BY_CATEGORY
};